name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Init submodules
      run: git submodule update
    - name: Build docs
      run: cargo rustdoc --lib
    - name: Build docs (with theme)
      run: cargo rustdoc --lib -- --extend-css "Better-Rust-Documentation/Better Rust documentation Dark Theme.css"